cureforall/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages/login'
  get 'pages/home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cureforall/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cureforall/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cureforall/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def login
  end

  
end

cureforall/app/helpers/application_helper.rb
module ApplicationHelper
end

cureforall/app/helpers/pages_helper.rb
module PagesHelper
end

cureforall/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cureforall</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %> -->
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>



  <%= yield %>

</html>

cureforall/app/views/pages/_footer.html.erb
<footer class="footer">
  © 2018
</footer>

cureforall/app/views/pages/_header.html.erb
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon --><b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <%= image_tag( (image_path "logo-icon.png"),  alt: "homepage", class: "dark-logo") %>
                    <!-- Light Logo icon -->
                    <%= image_tag( (image_path "logo-light-icon.png"),  alt: "homepage", class: "light-logo") %>

                    <!-- <img src="./Content/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" /> -->
                </b>
                <!--End Logo icon -->
                <!-- Logo text --><span>
                 <!-- dark Logo text -->
                 <%= image_tag( (image_path "logo-light-text.png"),  alt: "homepage", class: "dark-logo") %>

                 <!-- <img src="./Content/assets/images/logo-text.png" alt="homepage" class="dark-logo" /> -->
                 <!-- Light Logo text -->
                 <%= image_tag( (image_path "logo-light-text.png"),  alt: "homepage", class: "light-logo") %>

                 </span> </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->

        </div>
    </nav>
</header>

cureforall/app/views/pages/_login.html.erb
<section id="wrapper">
    <div class="login-register">
        <div class="login-box card">
            <div class="card-body">
                <form class="form-horizontal form-material" id="loginform" action="index.html">
                    <h3 class="box-title m-b-20">Sign In</h3>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Username"> </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Password"> </div>
                    </div>
                    <div class="form-group text-center">
                        <div class="col-xs-12 p-b-20">
                            <button class="btn btn-block btn-lg btn-info btn-rounded" type="submit">Log In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

cureforall/app/views/pages/_mainwrapper.html.erb
<div id="main-wrapper">
  <!-- ============================================================== -->
  <!-- Topbar header - style you can find in pages.scss -->
  <!-- ============================================================== -->
  <%= render partial: 'header' %>
  <!-- ============================================================== -->
  <!-- End Topbar header -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- Left Sidebar - style you can find in sidebar.scss  -->
  <!-- ============================================================== -->
  <%= render  partial:'pages/left/navbar'  %>
  <!-- ============================================================== -->
  <!-- End Left Sidebar - style you can find in sidebar.scss  -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- Page wrapper  -->
  <!-- ============================================================== -->
  <%= render partial: 'pages/wrapper/pagewrapper' %>
  <!-- ============================================================== -->
  <!-- End Page wrapper  -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- footer -->
  <!-- ============================================================== -->
  <%= render partial: 'footer' %>
  <!-- ============================================================== -->
  <!-- End footer -->
  <!-- ============================================================== -->
</div>

cureforall/app/views/pages/_preloader.html.erb
<div class="preloader">
    <div class="loader">
        <div class="loader__figure"></div>
        <p class="loader__label">admin</p>
    </div>
</div>

cureforall/app/views/pages/home.html.erb
<body class="skin-blue fixed-layout">
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <!-- <%= render partial: "preloader"%> -->
  <!-- ============================================================== -->
  <!-- Main wrapper - style you can find in pages.scss -->
  <!-- ============================================================== -->
  <%= render partial: "mainwrapper" %>
  <!-- ============================================================== -->
  <!-- End Wrapper -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- All Jquery -->
  <!-- ============================================================== -->
  <!-- <script src="./Content/assets/node_modules/jquery/jquery-3.2.1.min.js"></script> -->

  <!-- Bootstrap tether Core JavaScript -->
  <!-- <script src="./Content/assets/node_modules/popper/popper.min.js"></script> -->
  <!-- <script src="./Content/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script> -->

  <!-- slimscrollbar scrollbar JavaScript -->
  <!-- <script src="./Content/theme/dist/js/perfect-scrollbar.jquery.min.js"></script> -->

  <!--Wave Effects -->
  <!-- <script src="./Content/theme/dist/js/waves.js"></script> -->
  <%= javascript_include_tag (javascript_path("waves.js")) , 'data-turbolinks-track': 'reload' %>

  <!--Menu sidebar -->
  <!-- <script src="./Content/theme/dist/js/sidebarmenu.js"></script> -->
  <%= javascript_include_tag (javascript_path("sidebarmenu.js")) , 'data-turbolinks-track': 'reload' %>
  <!--stickey kit -->
  <!-- <script src="./Content/assets/node_modules/sticky-kit-master/dist/sticky-kit.min.js"></script> -->
  <%= javascript_include_tag (javascript_path("sticky-kit.min.js")) , 'data-turbolinks-track': 'reload' %>
  <!-- <script src="./Content/assets/node_modules/sparkline/jquery.sparkline.min.js"></script> -->
  <!--Custom JavaScript -->
  <!-- <script src="./Content/theme/dist/js/custom.min.js"></script> -->
  <%= javascript_include_tag (javascript_path("custom.min.js")) , 'data-turbolinks-track': 'reload' %>



</body>

cureforall/app/views/pages/left/_navbar.html.erb
<aside class="left-sidebar">
  <!-- Sidebar scroll-->
  <div class="scroll-sidebar">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
      <ul id="sidebarnav">
        <li><%= link_to pages_home_path,  :class => "waves-effect waves-dark", aria:{expanded: "false" } do %>
          <i class="fa fa-circle-o text-danger"></i><span class="hide-menu">Accueil</span>
          <% end %>
        </li>

        <li><%= link_to pages_login_path,  :class => "waves-effect waves-dark", aria:{expanded: "false" } do %>
          <i class="fa fa-circle-o text-succed"></i><span class="hide-menu">Log in</span>
          <% end %>
        </li>
        <li> <a class="waves-effect waves-dark" href="/Accueil/Annonces" aria-expanded="false"><i class="fa fa-circle-o text-info"></i><span class="hide-menu">Annonces</span></a></li>
      </ul>
    </nav>
    <!-- End Sidebar navigation -->
  </div>
  <!-- End Sidebar scroll-->
</aside>

cureforall/app/views/pages/login.html.erb
<body class="skin-blue card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
<!-- <%= render partial: "preloader"%> -->
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
<%= render partial: "login" %>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <!-- <script src="./Content/assets/node_modules/jquery/jquery-3.2.1.min.js"></script> -->
    <!-- Bootstrap tether Core JavaScript -->
    <!-- <script src="./Content/assets/node_modules/popper/popper.min.js"></script> -->
    <%= javascript_include_tag (javascript_path("popper.min.js"))  %>
    <!-- <script src="./Content/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script> -->
    <!--Custom JavaScript -->
    <script type="text/javascript">
        $(function() {
            $(".preloader").fadeOut();
        });
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()
        });
        // ==============================================================
        // Login and Recover Password
        // ==============================================================
        $('#to-recover').on("click", function() {
            $("#loginform").slideUp();
            $("#recoverform").fadeIn();
        });
    </script>

</body>

cureforall/app/views/pages/wrapper/_pagecontent.html.erb
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        This is some text within a card block.
      </div>
    </div>
  </div>
</div>

cureforall/app/views/pages/wrapper/_pagewrapper.html.erb
<div class="page-wrapper">
  <!-- ============================================================== -->
  <!-- Container fluid  -->
  <!-- ============================================================== -->
  <div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
      <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Blank Page</h4>
      </div>
      <div class="col-md-7 align-self-center text-right">
        <div class="d-flex justify-content-end align-items-center">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Blank Page</li>
          </ol>
        </div>
      </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <%= render partial: "pages/wrapper/pagecontent" %>
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
  </div>
  <!-- ============================================================== -->
  <!-- End Container fluid  -->
  <!-- ============================================================== -->
</div>